apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  name: asm-ingressgateway-multicluster-ingress
  namespace: asm-ingress
  annotations:
    networking.gke.io/static-ip: "34.110.222.38" # this will vary
    #kubernetes.io/ingress.allow-http: "false" # not recognized
    networking.gke.io/pre-shared-certs: "gke-mcg-ingress-cert"
spec:
  template:
    spec:
      backend:
       serviceName: asm-ingressgateway-multicluster-svc-1
       servicePort: 443
      rules:
        - host: 'frontend.endpoints.mc-e2m-01.cloud.goog'
          http:
            paths:
            - path: "/whereami.Whereami/*"
              backend:
                serviceName: asm-ingressgateway-multicluster-svc-1
                servicePort: 443
            - path: "/"
              backend:
                serviceName: asm-ingressgateway-multicluster-svc-1
                servicePort: 443
            