apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: whereami-grpc-vs
  namespace: whereami-grpc
  #namespace: asm-ingress
spec:
  gateways:
  - asm-ingress/whereami-gateway
  hosts:
  - 'frontend.endpoints.mc-e2m-01.cloud.goog'
  http:
  #- route:
  #  - destination:
  #      host: whereami-grpc
  #      port:
  #        number: 9090
  - name: "wherami-grpc"
    match:
    - uri:
        prefix: "/whereami.Whereami/"
        #regex: '^.*whereami\.Whereami.*$'
    - uri:
        prefix: "/grpc.reflection.v1alpha.ServerReflection/"
      #ignoreUriCase: true
    #rewrite:
    #  uri: "/whereami.Whereami.GetPayload"
    route:
    - destination:
        host: whereami-grpc
        port:
          number: 9090