apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: whereami-grpc-vs
  namespace: whereami-grpc
  #namespace: asm-ingress
spec:
  gateways:
  - asm-ingress/whereami-gateway
  hosts:
  - 'frontend.endpoints.mc-e2m-01.cloud.goog'
  http:
  - route:
    - destination:
        host: whereami-grpc
        port:
          number: 9090
  #- name: "base"
  #  match:
  #  - uri:
  #      exact: "/"
  #  route:
  #  - destination:
  #      host: whereami-grpc.whereami-grpc.svc.cluster.local
  #      port:
  #        number: 9090